steps:
- name: maven:3-jdk-8
  entrypoint: mvn
  args: ['package', '-Dmaven.skip.test=true']

#build docker container
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/project-one-300206/gameoflife', '--build-arg=JAR_FILE=target/*.war', '.']

#push container to container registry
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/project-one-300206/gameoflife']
  
#deploy to cloud run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'cloudrunservice'
  - '--image'
  - 'gcr.io/project-one-300206/gameoflife:latest'
  - '--region'
#  - 'us-central1'
  - 'europe-west3'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
#  timeout: 3600
#timeout: 3600
images:
  - 'gcr.io/project-one-300206/gameoflife:latest'
tags:
  - 'test-admin'
